fix: dump gateway errors during TLS handshake
ovrclk/akash pull request #1234
Opened 2021-04-29 21:54 UTC by troian

Signed-off-by: Artur Troian <troian.ap@gmail.com>

---
name: Pull Request
about: Submit a pull request
title: ''
labels: ''
assignees: '@boz @gosuri'

---

## Description

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/ovrclk/akash/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-05-05 04:01 UTC, boz requested changes
some comments inline - make it a bit less brittle and make it something that can be used elsewhere (`ctxlog`)

2021-05-05 04:01 UTC, boz commented on provider/gateway/utils/utils.go
> +						ctx.Value("log").(log.Logger).Error("VerifyPeerCertificate failed", "err", err.Error())
also, I *believe* that `err` will only be what you think it is here if it is declared like this:

```go
func(certificates [][]byte, _ [][]*x509.Certificate) (err error) {
```

2021-05-06 15:44 UTC, hydrogen18 commented
@troian can we close this?

2021-05-06 15:58 UTC, troian commented
yah

2021-05-06 15:58 UTC, closed without merging